import { library } from "@fortawesome/fontawesome-svg-core";
import type { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faBitbucket,
  faFacebook,
  faGithub,
  faGitlab,
  faGoogle,
  faInstagram,
  faLinkedin,
  faMicrosoft,
  faPaypal,
  faStackOverflow,
  faXTwitter,
} from "@fortawesome/free-brands-svg-icons";
import {
  faAlignCenter,
  faAlignJustify,
  faAlignLeft,
  faAlignRight,
  faArrowPointer,
  faArrowRightArrowLeft,
  faBars,
  faBarsProgress,
  faBicycle,
  faBold,
  faBook,
  faBookmark,
  faBug,
  faBuilding,
  faBullseye,
  faBus,
  faCableCar,
  faCalendarDays,
  faCar,
  faCaretDown,
  faCaretUp,
  faChartBar,
  faChartColumn,
  faChartLine,
  faChartPie,
  faChartSimple,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faCircleCheck,
  faCircleHalfStroke,
  faCircleInfo,
  faCirclePlus,
  faCircleQuestion,
  faClock,
  faClone,
  faClose,
  faCode,
  faComment,
  faCookieBite,
  faCopy,
  faCreditCard,
  faCross,
  faCrown,
  faCube,
  faDatabase,
  faDiagramProject,
  faDownload,
  faDrawPolygon,
  faEdit,
  faEllipsis,
  faEllipsisVertical,
  faEnvelope,
  faExpand,
  faExternalLinkAlt,
  faEye,
  faEyeSlash,
  faFerry,
  faFile,
  faFileInvoice,
  faFilter,
  faFloppyDisk,
  faFolder,
  faFolderPlus,
  faFont,
  faGears,
  faGlobe,
  faGripHorizontal,
  faGripVertical,
  faHashtag,
  faHouse,
  faImage,
  faInfo,
  faItalic,
  faLanguage,
  faLayerGroup,
  faLink,
  faList,
  faListOl,
  faListUl,
  faLocationCrosshairs,
  faLocationDot,
  faLocationPin,
  faLock,
  faMagnifyingGlassMinus,
  faMagnifyingGlassPlus,
  faMap,
  faMapLocationDot,
  faMaximize,
  faMinimize,
  faMinus,
  faMountain,
  faPalette,
  faPen,
  faPersonBiking,
  faPersonRunning,
  faPlane,
  faPlay,
  faPlus,
  faPrint,
  faQuestionCircle,
  faRefresh,
  faRocket,
  faRotateLeft,
  faRotateRight,
  faRoute,
  faRulerCombined,
  faRulerHorizontal,
  faSearch,
  faShare,
  faSignOut,
  faSliders,
  faSort,
  faSortAlphaDown,
  faSortAlphaUp,
  faStar,
  faStreetView,
  faStrikethrough,
  faSubscript,
  faSubway,
  faSuperscript,
  faT,
  faTable,
  faToolbox,
  faTrain,
  faTrainTram,
  faTrash,
  faUnderline,
  faUnlock,
  faUpload,
  faUser,
  faUserPlus,
  faUsers,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";
import { SvgIcon } from "@mui/material";
import type { SvgIconProps } from "@mui/material";

import {
  addImageIcon,
  aggregateIcon,
  arcgisFeatureServiceIcon,
  boundingBoxIcon,
  categories,
  circleEmpty,
  comingSoonIcon,
  dataCategoryIcon,
  divider,
  funicularIcon,
  geojsonIcon,
  gondolaIcon,
  h1,
  h2,
  h3,
  hexagonIcon,
  licenseIcon,
  lineIcon,
  northArrowCircleExtIcon,
  northArrowCircleIcon,
  northArrowCompassFilledIcon,
  northArrowCompassIcon,
  northArrowIcon,
  northArrowQuadrantIcon,
  number,
  pointIcon,
  polygonIcon,
  streetNetworkIcon,
  text,
  variableIcon,
  wfsIcon,
  wmsIcon,
  wmtsIcon,
  xyzIcon,
} from "../assets/svg/OtherIcons";

export enum ICON_NAME {
  // Solid icons
  ARROW_POINTER = "arrow-pointer",
  LAYERS = "layers",
  LEGEND = "legend",
  CHART = "chart",
  REPORT = "report",
  HELP = "help",
  TOOLBOX = "toolbox",
  FILTER = "filter",
  STYLE = "style",
  SIGNOUT = "signout",
  ORGANIZATION = "organization",
  MAP = "map",
  MAP_LOCATION = "map-location",
  CLOSE = "close",
  HOUSE = "house",
  HASHTAG = "hashtag",
  LETTER_T = "letter-t",
  FOLDER = "folder",
  FOLDER_NEW = "folder-new",
  SETTINGS = "settings",
  CIRCLECHECK = "circleCheck",
  CHECK = "check",
  CIRCLEINFO = "circleInfo",
  INFO = "info",
  OUTILINEDINFO = "outlinedInfo",
  EMAIL = "email",
  ROCKET = "rocket",
  PLUS = "plus",
  MINUS = "minus",
  MAXIMIZE = "maximize",
  MINIMIZE = "minimize",
  STAR = "star",
  ELLIPSIS = "ellipsis",
  SEARCH = "search",
  CHEVRON_LEFT = "chevron-left",
  CHEVRON_RIGHT = "chevron-right",
  CHEVRON_DOWN = "chevron-down",
  CHEVRON_UP = "chevron-up",
  EYE = "eye",
  EYE_SLASH = "eye-slash",
  MORE_VERT = "more-vert",
  MORE_HORIZ = "more-horiz",
  STEPUP = "step-up",
  STEPDOWN = "step-down",
  LOCATION = "location",
  LOCATION_MARKER = "location-marker",
  LOCATION_CROSSHAIRS = "location-crosshairs",
  CROSS = "cross",
  CIRCLE = "circle",
  CIRCLE_PLUS = "circle-plus",
  USER = "user",
  USERS = "users",
  LANGUAGE = "language",
  FILE = "file",
  GLOBE = "globe",
  EXTERNAL_LINK = "external-link",
  HAMBURGER_MENU = "hamburger-menu",
  SHARE = "share",
  TRASH = "trash",
  EDIT = "edit",
  XCLOSE = "xclose",
  EDITPEN = "editpen",
  SAVE = "save",
  DATABASE = "database",
  SORT = "sort",
  SORT_ALPHA_ASC = "sort-alpha-asc",
  SORT_ALPHA_DESC = "sort-alpha-desc",
  CLOCK = "clock",
  CALENDAR = "calendar",
  DOWNLOAD = "download",
  UPLOAD = "upload",
  TABLE = "table",
  BARS_PROGRESS = "bar-progress",
  CREDIT_CARD = "credit-card",
  RULES_COMBINED = "rules-combined",
  RULER_HORIZONTAL = "ruler-horizontal",
  CROWN = "crown",
  BULLSEYE = "bullsey",
  COPY = "copy",
  CHART_PIE = "chart-pie",
  ADD_USER = "add-user",
  EXPAND = "expand",
  SLIDERS = "sliders",
  ZOOM_IN = "zoom-in",
  ZOOM_OUT = "zoom-out",
  LINK = "link",
  REFRESH = "refresh",
  UNDO = "undo",
  REDO = "redo",
  DRAW_POLYGON = "draw-polygon",
  WORKFLOW = "workflow",
  VARIABLE = "variable",
  CLONE = "clone",
  MOUNTAIN = "mountain",
  ACCESSIBILITY = "accessibility",
  BOOK = "book",
  RUN = "run",
  BICYCLE = "bicycle",
  PEDELEC = "pedelec",
  BUS = "bus",
  CAR = "car",
  ROUTE = "route",
  TRAM = "tram",
  RAIL = "rail",
  SUBWAY = "subway",
  FERRY = "ferry",
  CABLE_CAR = "cable-car",
  FUNICULAR = "funicular",
  GONDOLA = "gondola",
  BUG = "bug",
  COOKIES = "cookies",
  LOCK = "lock",
  UNLOCK = "unlock",
  PLAY = "play",
  CUBE = "cube",
  GRIP_HORIZONTAL = "grip",
  GRIP_VERTICAL = "grip-vertical",
  IMAGE = "image",
  LIST = "list",
  BOOKMARK = "bookmark",
  COMMENT = "comment",
  FONT = "font",
  BOLD = "bold",
  ITALIC = "italic",
  UNDERLINE = "underline",
  STRIKETHROUGH = "strikethrough",
  SUPERSCRIPT = "superscript",
  SUBSCRIPT = "subscript",
  TEXT = "text",
  H1 = "h1",
  H2 = "h2",
  H3 = "h3",
  BULLET_LIST = "bullet-list",
  NUMBERED_LIST = "numbered-list",
  CODE = "code",
  ALIGN_RIGHT = "align-right",
  ALIGN_LEFT = "align-left",
  ALIGN_JUSTIFY = "align-justify",
  ALIGN_CENTER = "align-center",
  PLANE = "plane",
  PRINT = "print",
  // Brand icons
  GOOGLE = "google",
  MICROSOFT = "microsoft",
  FACEBOOK = "facebook",
  GITHUB = "github",
  GITLAB = "gitlab",
  STACKOVERFLOW = "stackoverflow",
  TWITTER = "twitter",
  LINKEDIN = "linkedin",
  INSTAGRAM = "instagram",
  BITBUCKET = "bitbucket",
  PAYPAL = "paypal",
  REVERSE = "reverse",
  // Custom icons
  ADD_IMAGE = "add-image",
  COMING_SOON = "coming-soon",
  AGGREGATE = "aggregate",
  HEXAGON = "hexagon",
  LICENSE = "license",
  DATA_CATEGORY = "data-category",
  LINE_CHART = "line-chart-icon",
  VERTICAL_BAR_CHART = "vertical-bar-chart",
  HORIZONTAL_BAR_CHART = "horizontal-bar-chart",
  BOUNDING_BOX = "bounding-box",
  POINT_FEATURE = "point-feature",
  LINE_FEATURE = "line-feature",
  POLYGON_FEATURE = "polygon-feature",
  STREET_NETWORK = "street-network",
  WMTS = "wmts",
  WMS = "wms",
  WFS = "wfs",
  XYZ = "xyz",
  ARCGIS_FEATURE_SERVICE = "arcgis-feature-service",
  GEOJSON = "geojson",
  PANEL_APPERANCE = "panel-appearance",
  PANEL_POSITION = "panel-position",
  DIVIDER = "divider",
  NUMBER = "number",
  CATEGORIES = "categories",
  CIRCLE_EMPTY = "circle-empty",
  LINE = "line",
  NORTH_ARROW = "north-arrow",
  NORTH_ARROW_CIRCLE = "north-arrow-circle",
  NORTH_ARROW_COMPASS = "north-arrow-compass",
  NORTH_ARROW_CIRCLE_EXT = "north-arrow-circle-ext",
  NORTH_ARROW_COMPASS_FILLED = "north-arrow-compass-filled",
  NORTH_ARROW_QUADRANT = "north-arrow-quadrant",
}

const nameToIcon: { [k in ICON_NAME]: IconDefinition } = {
  // Solid icons
  [ICON_NAME.ARROW_POINTER]: faArrowPointer,
  [ICON_NAME.LAYERS]: faLayerGroup,
  [ICON_NAME.LEGEND]: faList,
  [ICON_NAME.CHART]: faChartSimple,
  [ICON_NAME.REPORT]: faFileInvoice,
  [ICON_NAME.HELP]: faQuestionCircle,
  [ICON_NAME.TOOLBOX]: faToolbox,
  [ICON_NAME.FILTER]: faFilter,
  [ICON_NAME.STYLE]: faPalette,
  [ICON_NAME.SIGNOUT]: faSignOut,
  [ICON_NAME.ORGANIZATION]: faBuilding,
  [ICON_NAME.MAP]: faMap,
  [ICON_NAME.MAP_LOCATION]: faMapLocationDot,
  [ICON_NAME.CLOSE]: faClose,
  [ICON_NAME.HOUSE]: faHouse,
  [ICON_NAME.HASHTAG]: faHashtag,
  [ICON_NAME.LETTER_T]: faT,
  [ICON_NAME.FOLDER]: faFolder,
  [ICON_NAME.FOLDER_NEW]: faFolderPlus,
  [ICON_NAME.SETTINGS]: faGears,
  [ICON_NAME.CIRCLECHECK]: faCircleCheck,
  [ICON_NAME.CHECK]: faCheck,
  [ICON_NAME.CIRCLEINFO]: faCircleInfo,
  [ICON_NAME.INFO]: faInfo,
  [ICON_NAME.OUTILINEDINFO]: faCircleQuestion,
  [ICON_NAME.EMAIL]: faEnvelope,
  [ICON_NAME.ROCKET]: faRocket,
  [ICON_NAME.RUN]: faPersonRunning,
  [ICON_NAME.BUS]: faBus,
  [ICON_NAME.PLUS]: faPlus,
  [ICON_NAME.MINUS]: faMinus,
  [ICON_NAME.MAXIMIZE]: faMaximize,
  [ICON_NAME.MINIMIZE]: faMinimize,
  [ICON_NAME.ELLIPSIS]: faEllipsis,
  [ICON_NAME.SEARCH]: faSearch,
  [ICON_NAME.CHEVRON_LEFT]: faChevronLeft,
  [ICON_NAME.CHEVRON_RIGHT]: faChevronRight,
  [ICON_NAME.CHEVRON_DOWN]: faChevronDown,
  [ICON_NAME.CHEVRON_UP]: faChevronUp,
  [ICON_NAME.EYE]: faEye,
  [ICON_NAME.EYE_SLASH]: faEyeSlash,
  [ICON_NAME.STAR]: faStar,
  [ICON_NAME.MORE_VERT]: faEllipsisVertical,
  [ICON_NAME.MORE_HORIZ]: faEllipsis,
  [ICON_NAME.STEPUP]: faCaretUp,
  [ICON_NAME.STEPDOWN]: faCaretDown,
  [ICON_NAME.LOCATION]: faLocationDot,
  [ICON_NAME.LOCATION_MARKER]: faLocationPin,
  [ICON_NAME.LOCATION_CROSSHAIRS]: faLocationCrosshairs,
  [ICON_NAME.CROSS]: faCross,
  [ICON_NAME.CIRCLE]: faCircle,
  [ICON_NAME.CIRCLE_PLUS]: faCirclePlus,
  [ICON_NAME.USER]: faUser,
  [ICON_NAME.USERS]: faUsers,
  [ICON_NAME.LANGUAGE]: faLanguage,
  [ICON_NAME.FILE]: faFile,
  [ICON_NAME.GLOBE]: faGlobe,
  [ICON_NAME.HAMBURGER_MENU]: faBars,
  [ICON_NAME.SHARE]: faShare,
  [ICON_NAME.TRASH]: faTrash,
  [ICON_NAME.EDIT]: faEdit,
  [ICON_NAME.XCLOSE]: faXmark,
  [ICON_NAME.EDITPEN]: faPen,
  [ICON_NAME.SAVE]: faFloppyDisk,
  [ICON_NAME.DATABASE]: faDatabase,
  [ICON_NAME.SORT]: faSort,
  [ICON_NAME.SORT_ALPHA_ASC]: faSortAlphaUp,
  [ICON_NAME.SORT_ALPHA_DESC]: faSortAlphaDown,
  [ICON_NAME.CLOCK]: faClock,
  [ICON_NAME.CALENDAR]: faCalendarDays,
  [ICON_NAME.DOWNLOAD]: faDownload,
  [ICON_NAME.UPLOAD]: faUpload,
  [ICON_NAME.TABLE]: faTable,
  [ICON_NAME.BARS_PROGRESS]: faBarsProgress,
  [ICON_NAME.EXTERNAL_LINK]: faExternalLinkAlt,
  [ICON_NAME.CREDIT_CARD]: faCreditCard,
  [ICON_NAME.RULES_COMBINED]: faRulerCombined,
  [ICON_NAME.RULER_HORIZONTAL]: faRulerHorizontal,
  [ICON_NAME.CROWN]: faCrown,
  [ICON_NAME.REVERSE]: faArrowRightArrowLeft,
  [ICON_NAME.BULLSEYE]: faBullseye,
  [ICON_NAME.COPY]: faCopy,
  [ICON_NAME.PEDELEC]: faPersonBiking,
  [ICON_NAME.BICYCLE]: faBicycle,
  [ICON_NAME.CAR]: faCar,
  [ICON_NAME.SLIDERS]: faSliders,
  [ICON_NAME.ZOOM_IN]: faMagnifyingGlassPlus,
  [ICON_NAME.ZOOM_OUT]: faMagnifyingGlassMinus,
  [ICON_NAME.LINK]: faLink,
  [ICON_NAME.REFRESH]: faRefresh,
  [ICON_NAME.UNDO]: faRotateLeft,
  [ICON_NAME.REDO]: faRotateRight,
  [ICON_NAME.MOUNTAIN]: faMountain,
  [ICON_NAME.ACCESSIBILITY]: faStreetView,
  [ICON_NAME.DRAW_POLYGON]: faDrawPolygon,
  [ICON_NAME.WORKFLOW]: faDiagramProject,
  [ICON_NAME.VARIABLE]: variableIcon,
  [ICON_NAME.CLONE]: faClone,
  [ICON_NAME.BOOK]: faBook,
  [ICON_NAME.ROUTE]: faRoute,
  [ICON_NAME.TRAM]: faTrainTram,
  [ICON_NAME.RAIL]: faTrain,
  [ICON_NAME.SUBWAY]: faSubway,
  [ICON_NAME.FERRY]: faFerry,
  [ICON_NAME.CABLE_CAR]: faCableCar,
  [ICON_NAME.CHART_PIE]: faChartPie,
  [ICON_NAME.ADD_USER]: faUserPlus,
  [ICON_NAME.EXPAND]: faExpand,
  [ICON_NAME.BUG]: faBug,
  [ICON_NAME.COOKIES]: faCookieBite,
  [ICON_NAME.LOCK]: faLock,
  [ICON_NAME.UNLOCK]: faUnlock,
  [ICON_NAME.PLAY]: faPlay,
  [ICON_NAME.CUBE]: faCube,
  [ICON_NAME.GRIP_HORIZONTAL]: faGripHorizontal,
  [ICON_NAME.GRIP_VERTICAL]: faGripVertical,
  [ICON_NAME.IMAGE]: faImage,
  [ICON_NAME.LIST]: faList,
  [ICON_NAME.BOOKMARK]: faBookmark,
  [ICON_NAME.COMMENT]: faComment,
  [ICON_NAME.FONT]: faFont,
  [ICON_NAME.BOLD]: faBold,
  [ICON_NAME.ITALIC]: faItalic,
  [ICON_NAME.UNDERLINE]: faUnderline,
  [ICON_NAME.STRIKETHROUGH]: faStrikethrough,
  [ICON_NAME.SUPERSCRIPT]: faSuperscript,
  [ICON_NAME.SUBSCRIPT]: faSubscript,
  [ICON_NAME.H1]: h1,
  [ICON_NAME.H2]: h2,
  [ICON_NAME.H3]: h3,
  [ICON_NAME.TEXT]: text,
  [ICON_NAME.BULLET_LIST]: faListUl,
  [ICON_NAME.NUMBERED_LIST]: faListOl,
  [ICON_NAME.CODE]: faCode,
  [ICON_NAME.ALIGN_RIGHT]: faAlignRight,
  [ICON_NAME.ALIGN_LEFT]: faAlignLeft,
  [ICON_NAME.ALIGN_JUSTIFY]: faAlignJustify,
  [ICON_NAME.ALIGN_CENTER]: faAlignCenter,
  [ICON_NAME.PLANE]: faPlane,
  [ICON_NAME.PRINT]: faPrint,
  // Brand icons
  [ICON_NAME.GOOGLE]: faGoogle,
  [ICON_NAME.MICROSOFT]: faMicrosoft,
  [ICON_NAME.FACEBOOK]: faFacebook,
  [ICON_NAME.GITHUB]: faGithub,
  [ICON_NAME.GITLAB]: faGitlab,
  [ICON_NAME.STACKOVERFLOW]: faStackOverflow,
  [ICON_NAME.TWITTER]: faXTwitter,
  [ICON_NAME.LINKEDIN]: faLinkedin,
  [ICON_NAME.INSTAGRAM]: faInstagram,
  [ICON_NAME.BITBUCKET]: faBitbucket,
  [ICON_NAME.PAYPAL]: faPaypal,
  // Custom icons
  [ICON_NAME.ADD_IMAGE]: addImageIcon,
  [ICON_NAME.COMING_SOON]: comingSoonIcon,
  [ICON_NAME.FUNICULAR]: funicularIcon,
  [ICON_NAME.GONDOLA]: gondolaIcon,
  [ICON_NAME.AGGREGATE]: aggregateIcon,
  [ICON_NAME.HEXAGON]: hexagonIcon,
  [ICON_NAME.LICENSE]: licenseIcon,
  [ICON_NAME.DATA_CATEGORY]: dataCategoryIcon,
  [ICON_NAME.LINE_CHART]: faChartLine,
  [ICON_NAME.VERTICAL_BAR_CHART]: faChartColumn,
  [ICON_NAME.HORIZONTAL_BAR_CHART]: faChartBar,
  [ICON_NAME.BOUNDING_BOX]: boundingBoxIcon,
  [ICON_NAME.POINT_FEATURE]: pointIcon,
  [ICON_NAME.LINE_FEATURE]: lineIcon,
  [ICON_NAME.POLYGON_FEATURE]: polygonIcon,
  [ICON_NAME.STREET_NETWORK]: streetNetworkIcon,
  [ICON_NAME.WMTS]: wmtsIcon,
  [ICON_NAME.WMS]: wmsIcon,
  [ICON_NAME.WFS]: wfsIcon,
  [ICON_NAME.XYZ]: xyzIcon,
  [ICON_NAME.ARCGIS_FEATURE_SERVICE]: arcgisFeatureServiceIcon,
  [ICON_NAME.GEOJSON]: geojsonIcon,
  [ICON_NAME.PANEL_POSITION]: faAlignCenter,
  [ICON_NAME.PANEL_APPERANCE]: faCircleHalfStroke,
  [ICON_NAME.DIVIDER]: divider,
  [ICON_NAME.NUMBER]: number,
  [ICON_NAME.CATEGORIES]: categories,
  [ICON_NAME.CIRCLE_EMPTY]: circleEmpty,
  [ICON_NAME.LINE]: lineIcon,
  [ICON_NAME.NORTH_ARROW]: northArrowIcon,
  [ICON_NAME.NORTH_ARROW_CIRCLE]: northArrowCircleIcon,
  [ICON_NAME.NORTH_ARROW_COMPASS]: northArrowCompassIcon,
  [ICON_NAME.NORTH_ARROW_CIRCLE_EXT]: northArrowCircleExtIcon,
  [ICON_NAME.NORTH_ARROW_COMPASS_FILLED]: northArrowCompassFilledIcon,
  [ICON_NAME.NORTH_ARROW_QUADRANT]: northArrowQuadrantIcon,
};

interface BrandColors {
  [key: string]: string;
}
export const brandColors: BrandColors = {
  [ICON_NAME.GOOGLE]: "#4285F4",
  [ICON_NAME.MICROSOFT]: "#00A4EE",
  [ICON_NAME.FACEBOOK]: "#3B5998",
  [ICON_NAME.GITHUB]: "#333333",
  [ICON_NAME.GITLAB]: "#FCA121",
  [ICON_NAME.STACKOVERFLOW]: "#FE7A15",
  [ICON_NAME.TWITTER]: "#1DA1F2",
  [ICON_NAME.LINKEDIN]: "#0077B5",
  [ICON_NAME.INSTAGRAM]: "#E1306C",
  [ICON_NAME.BITBUCKET]: "#0052CC",
  [ICON_NAME.PAYPAL]: "#0079C1",
};

library.add(...Object.values(nameToIcon));

/** An icon's raw geometry: its own viewBox size and the path data behind it.
 * `null` for a name the map has no icon for. */
function iconGeometry(iconName: ICON_NAME): { width: number; height: number; paths: string[] } | null {
  const def = nameToIcon[iconName];
  if (!def) return null;
  const [width, height, , , svgPathData] = def.icon;
  return { width, height, paths: Array.isArray(svgPathData) ? svgPathData : [svgPathData] };
}

export function Icon({ iconName, ...rest }: SvgIconProps & { iconName: ICON_NAME }): React.JSX.Element {
  const geometry = iconGeometry(iconName);
  if (!geometry) throw new Error(`Invalid icon name: ${iconName}`);

  return (
    <SvgIcon viewBox={`0 0 ${geometry.width} ${geometry.height}`} {...rest}>
      {geometry.paths.map((d, i) => (
        <path key={i} d={d} fill="currentColor" />
      ))}
    </SvgIcon>
  );
}
